data:
  integrated_file: integrated_with_external.parquet
  processed_dir: data/processed
features:
  optimal_features:
  - RSI
  - Price_vs_MA5
  - Price_vs_MA20
  - Volatility
  - Volume_Ratio
  - Momentum_5
  - Momentum_20
  - Price_Position
model:
  accuracy: 0.56
  config:
    max_depth: 3
    min_child_samples: 20
    n_estimators: 100
    subsample: 0.8
    colsample_bytree: 0.8
  type: LightGBM
optimal_params:
  annual_return: 1.2321
  hold_days: 9
  last_updated: '2025-09-06'
  profit_target: 0.14
  stop_loss: 0.06
optimization:
  hold_days_range:
  - 1
  - 10
  max_cpu_cores: 8
  profit_target_range:
  - 0.01
  - 0.2
  - 0.01
  progress_report_interval: 100
  stop_loss_range:
  - 0.01
  - 0.15
  - 0.01
  validation_periods:
    recent_1year: 252
    recent_3months: 63
    recent_6months: 126
reports:
  daily_backup: true
  include_charts: true
  output_dir: production_reports
system:
  confidence_threshold: 0.52
  initial_capital: 1000000
  max_positions: 5
  transaction_cost_rate: 0.001
